FactoryGirl.define do
  factory :profile do
    association :user, factory: :user, strategy: :build
    first_name "John"
    middle_name "A."
    last_name "Doe"
    sequence(:ciese_id) { |n| n }
    prefix "Prefix"
    title "Title"
    greeting "Greeting"
    ssn "Social Security Number"
    email1 "Email 1"
    email2 "Email 2"
    department "Department"
    subject "Subject"
    grade "Grade"
    function "Function"
    district "District"
    affiliation "Affiliation"
    address_line_1 "Address Line 1"
    address_line_2 ""
    city "City"
    state "State"
    zip "11111"
    country "Country"
    phone1 "123-456-7890"
    phone2 "456-789-0123"
    fax "789-012-3456"
    home_address_line_1 "Home Address Line 1"
    home_address_line_2 ""
    home_city "Home City"
    home_state "Home State"
    home_zip "22222"
    home_phone "555-232-3232"
    home_mobile "555-111-2222"
    home_fax "555-222-1111"
    memo1 "This memo has some information."
    memo2 ""
    memo3 ""
  end
end
