development:
  adapter: postgresql
  encoding: unicode
  database: ciese-dev
  username: ciese

test:
  adapter: postgresql
  encoding: unicode
  database: ciese-test
  username: ciese

production:
  adapter: postgresql
  encoding: unicode
  database: ciese-prod
  username: ciese
